### ISSUE TITLE
PID 값 0x9091은 모든 픽셀 기종에 동일한 것 같습니다

### ISSUE THREAD

**Issue by nooriro** [gheron772/Pixel3aVoLTE#1]
Pixel 2 XL에서의 diag mode 진입을 위해 [AGagarin](https://github.com/AGagarin/Magisk)님이 수정한 `magiskrc.h`의  [36행부터](https://github.com/AGagarin/Magisk/blob/4db651f7992cc4d5c138edf5d0a673a0d7de2130/native/jni/core/magiskrc.h#L36)를 보면,
```
"on property:sys.usb.ffs.ready=1 && property:sys.usb.config=diag,serial_cdev,rmnet_gsi,adb && property:sys.usb.configfs=1\n"
...
"    write /config/usb_gadget/g1/idVendor 0x05C6\n"
"    write /config/usb_gadget/g1/idProduct 0x9091\n"
...
```
* `sys.usb.ffs.ready` 값이 `1`
* `sys.usb.config` 값이 `diag,serial_cdev,rmnet_gsi,adb`
* `sys.usb.configfs` 값이 `1`

세 시스템 프로퍼티의 값이 모두 위와 같이 설정되면, USB 기기의 VID와 PID가 각각 `0x05C6`, `0x9091`로 설정되는 것 같습니다.

한편, [wahoo](https://www.xda-developers.com/wahoo-google-pixel-2018/)의 `UsbGadget.cpp`에서 `0x9091`로 문자열 검색을 해 보면 [딱 한 곳에서](https://android.googlesource.com/device/google/wahoo/+/android-10.0.0_r26/usb/UsbGadget.cpp#364) 검색됩니다.
```
case static_cast<uint64_t>(GadgetFunction::ADB):
    ...
    } else if (vendorFunctions == "diag,serial_cdev,rmnet_gsi") {
        ret = setVidPid("0x05C6", "0x9091");
    } ...
    ...
    break;
```

위와 같은 부분을 다른 픽셀 기종의 `UsbGadget.cpp`에서도 찾아보면, 모든 기종에서 VID는 `0x05C6`, PID는 `0x9091`로 동일하게 설정되는 것을 확인할 수 있습니다. 
* [`UsbGadget.cpp`, Line 364 - Pixel 2/XL, QQ1A.200205.002](https://android.googlesource.com/device/google/wahoo/+/android-10.0.0_r26/usb/UsbGadget.cpp#364)
* [`UsbGadget.cpp`, Line 389 - Pixel 3/XL, QQ1A.200205.002](https://android.googlesource.com/device/google/crosshatch/+/android-10.0.0_r26/usb/UsbGadget.cpp#389)
* [`UsbGadget.cpp`, Line 389 - Pixel 3a/XL, QQ1A.200205.002](https://android.googlesource.com/device/google/bonito/+/android-10.0.0_r26/usb/UsbGadget.cpp#389)
* [`UsbGadget.cpp`, Line 151 - Pixel 4/XL, QQ1B.200205.002](https://android.googlesource.com/device/google/coral/+/android-10.0.0_r27/usb/UsbGadget.cpp#151)

따라서 [AGagarin](https://github.com/AGagarin/Magisk)님이 수정한 [`magiskrc.h`](https://github.com/AGagarin/Magisk/blob/4db651f7992cc4d5c138edf5d0a673a0d7de2130/native/jni/core/magiskrc.h)에 나온 PID 값 `0x9091`을 기종에 따라 다른 값으로 바꿔서는 안 된다고 생각합니다.

**Comment by gheron772** [comment]
제가 코드 확인하는 과정에서 실수가 있었습니다.
해당 내용은 삭제하도록 하겠습니다.

상세한 이력확인에 대해 감사 드립니다.
